# Setup
title:               Ritiek Malhotra
tagline:             'Just some of my adventures!'

# description:         '<a href="https://github.com/ritiek" target="_blank">GitHub</a>,
#                       <a href="https://stackoverflow.com/users/6554943/ritiek">Stack Overflow</a>,
#                       <a href="https://www.reddit.com/user/Ritiek">Reddit</a><br>
#                       <!-- <a href="https://www.linkedin.com/in/ritiek/">LinkedIn</a><br> -->
#                       <br>
#                       Reach me at<br>
#                       <a href="mailto:ritiekmalhotra123@gmail.com">ritiekmalhotra123@gmail.com</a><br>'
# description:         Peices on technology!
description:         Just some of my adventures!

url:                 https://ritiek.github.io
baseurl:             ''
paginate:            3
permalink:           pretty

# About/contact
author:
  name:              Ritiek Malhotra
  url:               https://ritiek.github.io/
  email:             ritiekmalhotra123@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
google_analytics_id: #UA-XXXX-Y
